image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start containers
    command: docker-compose up -d

ports:
  - port: 5432
    onOpen: ignore
    description: PostgreSQL
  - port: 5050
    onOpen: open-browser
    description: PgAdmin

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - eamodio.gitlens
